import pandas as pd

from config import BASE, N_SAMPLE_FILES

annotations = {
    1: {
        1: "None", 2: "None", 3: "Political/Ideological", 4: "None", 5: "Age-based",
        6: "Gender-based", 7: "None", 8: "Sexual orientation; Racial/Ethnic/National", 9: "Political/Ideological", 10: "Gender-based",
        11: "Racial/Ethnic/National", 12: "Gender-based", 13: "None", 14: "None", 15: "None",
        16: "None", 17: "None", 18: "Gender-based", 19: "Racial/Ethnic/National", 20: "Class/Occupation",
        21: "None", 22: "Gender-based", 23: "Gender-based", 24: "Racial/Ethnic/National", 25: "None",
        26: "None", 27: "Racial/Ethnic/National", 28: "Gender-based", 29: "None", 30: "None",
        31: "None", 32: "Racial/Ethnic/National", 33: "None", 34: "Sexual orientation", 35: "Gender-based",
        36: "None", 37: "None", 38: "None", 39: "Class/Occupation", 40: "Religion-based",
        41: "None", 42: "Gender-based", 43: "Class/Occupation", 44: "None", 45: "Gender-based",
        46: "None", 47: "Religion-based", 48: "None", 49: "Age-based", 50: "None",
        51: "None", 52: "Racial/Ethnic/National", 53: "Racial/Ethnic/National; Gender-based", 54: "Sexual orientation", 55: "None",
        56: "Appearance/Physical condition", 57: "Class/Occupation", 58: "None", 59: "Racial/Ethnic/National", 60: "None",
        61: "Racial/Ethnic/National", 62: "None", 63: "None", 64: "None", 65: "Gender-based; Appearance/Physical condition",
        66: "Racial/Ethnic/National; Gender-based", 67: "None", 68: "Racial/Ethnic/National", 69: "Gender-based", 70: "None",
        71: "None", 72: "None", 73: "None", 74: "Racial/Ethnic/National", 75: "None",
        76: "Gender-based", 77: "None", 78: "Religion-based; Gender-based", 79: "None", 80: "None",
        81: "None", 82: "None", 83: "Religion-based", 84: "Racial/Ethnic/National; Religion-based", 85: "None",
        86: "Religion-based", 87: "Political/Ideological", 88: "None", 89: "Racial/Ethnic/National", 90: "None",
        91: "None", 92: "None", 93: "Gender-based", 94: "None", 95: "None",
        96: "None", 97: "Racial/Ethnic/National", 98: "None", 99: "None", 100: "None",
    },
    2: {
        1: "Appearance/Physical condition", 2: "None", 3: "None", 4: "Sexual orientation", 5: "Sexual orientation",
        6: "None", 7: "Racial/Ethnic/National", 8: "None", 9: "None", 10: "None",
        11: "None", 12: "None", 13: "None", 14: "Racial/Ethnic/National", 15: "Racial/Ethnic/National",
        16: "None", 17: "Gender-based", 18: "Religion-based", 19: "Gender-based; Sexual orientation", 20: "None",
        21: "None", 22: "Appearance/Physical condition", 23: "None", 24: "Political/Ideological; Racial/Ethnic/National", 25: "Racial/Ethnic/National",
        26: "None", 27: "None", 28: "None", 29: "Religion-based", 30: "None",
        31: "None", 32: "Class/Occupation", 33: "None", 34: "Appearance/Physical condition", 35: "None",
        36: "None", 37: "Gender-based; Age-based", 38: "Racial/Ethnic/National", 39: "Age-based", 40: "Racial/Ethnic/National",
        41: "None", 42: "Gender-based", 43: "None", 44: "None", 45: "None",
        46: "None", 47: "Political/Ideological", 48: "None", 49: "None", 50: "None",
        51: "None", 52: "Political/Ideological; Racial/Ethnic/National", 53: "Racial/Ethnic/National", 54: "None", 55: "Religion-based",
        56: "Racial/Ethnic/National; Religion-based", 57: "Age-based", 58: "None", 59: "Racial/Ethnic/National", 60: "Sexual orientation",
        61: "None", 62: "None", 63: "None", 64: "Appearance/Physical condition", 65: "None",
        66: "None", 67: "None", 68: "Racial/Ethnic/National", 69: "Class/Occupation", 70: "None",
        71: "Religion-based", 72: "Class/Occupation", 73: "Mental health", 74: "Sexual orientation", 75: "None",
        76: "Class/Occupation", 77: "None", 78: "None", 79: "Political/Ideological", 80: "Religion-based; Age-based",
        81: "None", 82: "Gender-based", 83: "None", 84: "None", 85: "Political/Ideological; Racial/Ethnic/National; Religion-based",
        86: "Religion-based", 87: "None", 88: "None", 89: "None", 90: "None",
        91: "None", 92: "None", 93: "Political/Ideological; Racial/Ethnic/National", 94: "Gender-based; Political/Ideological", 95: "None",
        96: "None", 97: "Political/Ideological; Racial/Ethnic/National", 98: "None", 99: "None", 100: "Political/Ideological",
    },
    3: {
        1: "None", 2: "None", 3: "None", 4: "None", 5: "None",
        6: "None", 7: "None", 8: "Racial/Ethnic/National; Sexual orientation", 9: "None", 10: "None",
        11: "Racial/Ethnic/National", 12: "None", 13: "None", 14: "None", 15: "None",
        16: "None", 17: "Racial/Ethnic/National", 18: "None", 19: "None", 20: "Religion-based",
        21: "Class/Occupation", 22: "None", 23: "None", 24: "None", 25: "Political/Ideological",
        26: "Class/Occupation; Religion-based", 27: "Gender-based", 28: "None", 29: "Political/Ideological", 30: "Racial/Ethnic/National",
        31: "None", 32: "Gender-based; Political/Ideological", 33: "None", 34: "None", 35: "Gender-based",
        36: "Gender-based; Appearance/Physical condition", 37: "Gender-based", 38: "None", 39: "Gender-based", 40: "None",
        41: "Gender-based", 42: "Gender-based; Racial/Ethnic/National", 43: "Racial/Ethnic/National; Age-based", 44: "None", 45: "None",
        46: "Class/Occupation", 47: "None", 48: "None", 49: "None", 50: "None",
        51: "None", 52: "Racial/Ethnic/National", 53: "None", 54: "Sexual orientation", 55: "Racial/Ethnic/National",
        56: "None", 57: "Gender-based", 58: "Racial/Ethnic/National; Political/Ideological", 59: "None", 60: "Class/Occupation",
        61: "Racial/Ethnic/National", 62: "None", 63: "None", 64: "Mental health", 65: "Appearance/Physical condition",
        66: "None", 67: "None", 68: "None", 69: "None", 70: "None",
        71: "None", 72: "None", 73: "Racial/Ethnic/National; Political/Ideological", 74: "None", 75: "None",
        76: "Class/Occupation", 77: "Racial/Ethnic/National; Political/Ideological", 78: "Religion-based; Gender-based", 79: "None", 80: "None",
        81: "Gender-based", 82: "None", 83: "Racial/Ethnic/National; Religion-based", 84: "Class/Occupation; Gender-based", 85: "None",
        86: "Political/Ideological", 87: "None", 88: "None", 89: "None", 90: "Age-based",
        91: "Age-based; Gender-based", 92: "Racial/Ethnic/National", 93: "None", 94: "None", 95: "None",
        96: "Sexual orientation", 97: "None", 98: "Age-based", 99: "None", 100: "Class/Occupation",
    },
    4: {
        1: "Racial/Ethnic/National; Age-based", 2: "None", 3: "None", 4: "None", 5: "None",
        6: "None", 7: "Racial/Ethnic/National; Political/Ideological", 8: "None", 9: "Racial/Ethnic/National; Religion-based", 10: "Appearance/Physical condition",
        11: "None", 12: "None", 13: "None", 14: "Religion-based", 15: "None",
        16: "None", 17: "Age-based", 18: "Gender-based", 19: "Racial/Ethnic/National", 20: "None",
        21: "None", 22: "Racial/Ethnic/National; Political/Ideological", 23: "Class/Occupation; Gender-based", 24: "Gender-based", 25: "None",
        26: "Political/Ideological", 27: "None", 28: "None", 29: "Gender-based", 30: "None",
        31: "None", 32: "None", 33: "None", 34: "None", 35: "None",
        36: "Religion-based", 37: "Class/Occupation", 38: "Racial/Ethnic/National", 39: "Religion-based; Age-based", 40: "None",
        41: "None", 42: "Class/Occupation", 43: "None", 44: "Class/Occupation", 45: "Appearance/Physical condition; Gender-based; Mental health",
        46: "None", 47: "None", 48: "Religion-based; Age-based", 49: "None", 50: "None",
        51: "None", 52: "None", 53: "Religion-based; Racial/Ethnic/National", 54: "Gender-based", 55: "Racial/Ethnic/National; Appearance/Physical condition",
        56: "None", 57: "None", 58: "None", 59: "Gender-based", 60: "None",
        61: "None", 62: "None", 63: "None", 64: "Sexual orientation", 65: "Religion-based; Age-based",
        66: "Racial/Ethnic/National", 67: "Class/Occupation", 68: "Sexual orientation", 69: "Religion-based", 70: "Gender-based",
        71: "None", 72: "Racial/Ethnic/National", 73: "Age-based", 74: "None", 75: "Racial/Ethnic/National",
        76: "Political/Ideological; Gender-based", 77: "Gender-based", 78: "Racial/Ethnic/National; Political/Ideological", 79: "None", 80: "Racial/Ethnic/National",
        81: "None", 82: "Racial/Ethnic/National", 83: "None", 84: "None", 85: "None",
        86: "Racial/Ethnic/National; Mental health", 87: "Appearance/Physical condition", 88: "Gender-based", 89: "None", 90: "Appearance/Physical condition",
        91: "None", 92: "Political/Ideological; Racial/Ethnic/National", 93: "None", 94: "Gender-based; Class/Occupation", 95: "None",
        96: "Political/Ideological; Class/Occupation", 97: "Racial/Ethnic/National; Class/Occupation", 98: "None", 99: "None", 100: "Racial/Ethnic/National",
    },
    5: {
        1: "None", 2: "None", 3: "None", 4: "None", 5: "None",
        6: "None", 7: "Political/Ideological", 8: "None", 9: "None", 10: "None",
        11: "Appearance/Physical condition", 12: "Racial/Ethnic/National", 13: "None", 14: "None", 15: "Gender-based",
        16: "None", 17: "None", 18: "None", 19: "Age-based", 20: "None",
        21: "Gender-based", 22: "None", 23: "None", 24: "None", 25: "None",
        26: "None", 27: "None", 28: "None", 29: "None", 30: "None",
        31: "Racial/Ethnic/National", 32: "None", 33: "Gender-based", 34: "Racial/Ethnic/National; Religion-based; Political/Ideological", 35: "None",
        36: "None", 37: "None", 38: "Racial/Ethnic/National", 39: "None", 40: "Appearance/Physical condition; Mental health",
        41: "None", 42: "Religion-based", 43: "None", 44: "Racial/Ethnic/National", 45: "None",
        46: "Gender-based", 47: "None", 48: "None", 49: "None", 50: "Mental health",
        51: "Political/Ideological", 52: "None", 53: "None", 54: "Gender-based", 55: "Racial/Ethnic/National",
        56: "None", 57: "None", 58: "None", 59: "Class/Occupation", 60: "Gender-based",
        61: "None", 62: "Sexual orientation", 63: "None", 64: "None", 65: "None",
        66: "None", 67: "Religion-based; Mental health", 68: "Racial/Ethnic/National; Religion-based", 69: "Racial/Ethnic/National", 70: "Age-based",
        71: "None", 72: "None", 73: "None", 74: "Religion-based; Racial/Ethnic/National", 75: "None",
        76: "Appearance/Physical condition", 77: "None", 78: "None", 79: "None", 80: "Gender-based",
        81: "None", 82: "Racial/Ethnic/National", 83: "Racial/Ethnic/National", 84: "None", 85: "Racial/Ethnic/National; Gender-based",
        86: "Appearance/Physical condition; Mental health", 87: "Class/Occupation", 88: "None", 89: "Sexual orientation", 90: "Gender-based",
        91: "None", 92: "None", 93: "None", 94: "Class/Occupation", 95: "Racial/Ethnic/National; Political/Ideological",
        96: "None", 97: "None", 98: "Gender-based", 99: "None", 100: "None",
    },
}

for i in range(1, N_SAMPLE_FILES + 1):
    path = BASE / f"sample_{i}.csv"
    df = pd.read_csv(path, index_col="id")
    df["category_llm"] = df.index.map(annotations[i])
    df.to_csv(path, index_label="id")
    counts = df["category_llm"].value_counts()
    categorized = (df["category_llm"] != "None").sum()
    print(f"sample_{i}.csv — {categorized}/100 jokes categorized")

print("\nDone.")
