"""
Scatter plot: individual joke win rate vs joke length, color-coded by category.
Requires joke_winrates.json (generated by joke_winrates.py).

Usage: python3.11 length_scatter.py
"""

import json
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.lines as mlines
from pathlib import Path
from scipy import stats

BASE        = Path(__file__).parent
FIGURES_DIR = BASE / "figures"
FIGURES_DIR.mkdir(exist_ok=True)

PALETTE = {
    "Class/Occupation":             "#2ecc71",
    "Religion-based":               "#1a9952",
    "Age-based":                    "#95a5a6",
    "Gender-based":                 "#7f8c8d",
    "Mental health":                "#e67e22",
    "Political/Ideological":        "#e74c3c",
    "Appearance/Physical condition":"#c0392b",
    "Racial/Ethnic/National":       "#8e44ad",
    "Sexual orientation":           "#6c3483",
}

SHORT = {
    "Class/Occupation":             "Class/Occ.",
    "Religion-based":               "Religion",
    "Age-based":                    "Age",
    "Gender-based":                 "Gender",
    "Mental health":                "Mental health",
    "Political/Ideological":        "Political",
    "Appearance/Physical condition":"Appearance",
    "Racial/Ethnic/National":       "Racial/Ethnic",
    "Sexual orientation":           "Sexual orient.",
}

# ── Load joke win rates ───────────────────────────────────────────────────────
with open(BASE / "joke_winrates.json") as f:
    winrates = json.load(f)

jokes    = list(winrates.keys())
lengths  = [len(j) for j in jokes]
rates    = [winrates[j]["win_rate"] for j in jokes]
cats     = [winrates[j]["category"] for j in jokes]
colors   = [PALETTE.get(c, "#aaaaaa") for c in cats]

lengths = np.array(lengths)
rates   = np.array(rates)

# ── Global regression line ────────────────────────────────────────────────────
slope, intercept, r, p, _ = stats.linregress(lengths, rates)
x_line = np.linspace(lengths.min(), lengths.max(), 300)
y_line = slope * x_line + intercept

# ── Figure ────────────────────────────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(12, 6))

ax.scatter(lengths, rates, c=colors, alpha=0.18, s=8,
           linewidths=0, zorder=2)

ax.plot(x_line, y_line, color="black", linewidth=1.8,
        linestyle="--", zorder=4,
        label=f"Regression  r={r:+.3f}  p={p:.2f}")

ax.axhline(0.5, color="gray", linewidth=1, linestyle=":", alpha=0.6)

# Cap x-axis at 99th percentile to avoid extreme outliers crushing the view
cap = int(np.percentile(lengths, 99))
ax.set_xlim(0, cap)
ax.set_ylim(-0.05, 1.05)

ax.set_xlabel("Joke length (characters)", fontsize=11)
ax.set_ylabel("Individual win rate", fontsize=11)
ax.set_title(
    "Win rate vs. joke length — one dot per joke, color = category\n"
    f"(x-axis capped at 99th percentile = {cap} chars)",
    fontsize=11, pad=12,
)
ax.yaxis.grid(True, linestyle="--", alpha=0.3, zorder=0)
ax.set_axisbelow(True)
ax.spines[["top", "right"]].set_visible(False)

# Legend: one entry per category
handles = [
    mlines.Line2D([], [], marker="o", linestyle="None",
                  color=PALETTE[c], markersize=7, alpha=0.8, label=SHORT[c])
    for c in PALETTE
]
handles.append(
    mlines.Line2D([], [], color="black", linewidth=1.5,
                  linestyle="--", label=f"Regression  r={r:+.3f}  p={p:.2f}")
)
ax.legend(handles=handles, fontsize=8, loc="upper right",
          framealpha=0.9, ncol=2)

plt.tight_layout()
out = FIGURES_DIR / "length_winrate_scatter.png"
plt.savefig(out, dpi=180, bbox_inches="tight")
plt.close()
print(f"✓ figures/length_winrate_scatter.png")
